services:
  - type: web
    name: lbs-static-site
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false

  - type: web
    name: lbs-api
    runtime: node
    rootDir: api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
    pullRequestPreviewsEnabled: false
