services:
  - type: web
    name: lbs-static-site
    env: node
    buildCommand: npm install
    startCommand: npm start
    pullRequestPreviewsEnabled: false
    envVars:
      - key: PORT
        value: 10000
