services:
  - type: web
    name: lbsconnect
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
    pullRequestPreviewsEnabled: false
